### ISSUE TITLE
Add Fee Type: Transit Center Open Space Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#68]
Transit Center Open Space Fee
Planning Code Section 424.6
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_424.6

This fee addresses the impact on parks and recreational facilities created by the increased development permitted under the Transit Center District Plan. It applies to all projects in the Transit Center Special Use District and is triggered by (1) the addition of a dwelling unit, (2) the addition of 800 square feet of space or (3) the creation of any new use subject to higher fees than the use it replaces. Fees vary depending on use and increase for square footage beyond a Floor Area Ratio (FAR) of 9:1. There are additional options for compliance with this fee, including in-kind provision of open space.

**Comment by robgaston** [comment]
@mikewynne the fee schedule [here](https://github.com/sfcpc/ifc/blob/71_transit_center_open_space/fees/transit-center-open-space/info.md) declares different fees for different types of use.

Should the FAR be calculated per use type here (for example: net new residential GSF / parcel area) or should we use the total project area in calculating FAR?

If the latter, in the case of a mixed-use project, how should we determine which uses to apply to the base fee vs. the GSF above 9:1 fee?

**Comment by mikewynne** [comment]
CPC staff who are experts on this fee and are assigned to test the fee. 
Area experts: Nick Foster
General experts: Josephine Chen, Sylvia Jimenez
All-fee experts: Corey Teague, Mat Snyder

**Comment by mikewynne** [comment]
Two issues:
1.  Under the calculate page all of the new addition types (retail, hotel, etc.) are listed but Office is not (because it's on the trigger page).  This is confusing some users.  Can we add Office to the calculate page and pre-populate it with the number entered in the trigger page?
2. The FAR > 9:1 proportioning does not appear to be working correctly, it's always appearing as N/A or 0 for the GSF.  The FAR ratio should relate to the entire project - so if the whole project has a FAR > 9:1 then the FAR proportioning should occur.

**Comment by adamlodge** [comment]
Saving for pair-programming with Mike at the end of the project.

**Comment by mikewynne** [comment]
Closing this fee, we think it's now correct although Corey feels that it won't be used again so suspending QAing and shifting to 'Closed'.
