### ISSUE TITLE
Add Fee Type: Eastern Neighborhoods Residential Open Space Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#77]
Eastern Neighborhoods Residential Open Space Fee
Planning Code Section 427(a)
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_427

This fee addresses the impact on parks and open spaces from development projects that seek to not provide the otherwise-required on-site open space. It is available only in Eastern Neighborhoods Mixed Use Districts to residential projects that receive a Variance or exception from providing the required amount of Usable Open Space.

**Comment by ryan86** [comment]
@mikewynne Is this fee triggered by the criteria in 329(b) (>75 ft in height or >25000 gfa) or the criteria in 423.3(b) or some combination or neither?

**Comment by mikewynne** [comment]
@robgaston Very similar to the non-res fee, can we simplify this to just have the planner enter the shortfall of OS that has been provided.  That would mean that we could also remove the publicly accessible checkbox.  And can you check that the fee number from the Impact Fee Schedule is being used, rather than the number listed in the planning code.

**Comment by robgaston** [comment]
@mikewynne this fee has been updated to simply collect the shortfall of OS; also I've updated w/ the latest fee schedule. Thanks!

**Comment by mikewynne** [comment]
@robgaston This one is good.  Thanks.
